foreground = "#FFFFFF"
background = "#000000"
black = "#000000"
red = "#AA0000"
green = "#00AA00"
yellow = "#AAAA00"
blue = "#0000AA"
magenta = "#AA00AA"
cyan = "#00AAAA"
white = "#AAAAAA"
bright_black = "#555555"
bright_red = "#FF5555"
bright_green = "#55FF55"
bright_yellow = "#FFFF55"
bright_blue = "#5555FF"
bright_magenta = "#FF55FF"
bright_cyan = "#55FFFF"
bright_white = "#FFFFFF"
